version: '3.3'
services:
  backend:
    build: .
    ports: 
      - 8000:3000
    volumes: 
      - .:/app
    depends_on: 
      - db


  db:
    image: mysql:8.0.26
    restart: always
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: root_u
      MYSQL_PASSWORD: root_u
      MYSQL_ROOT_PASSWORD: root_u
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33066:3306

